// Generated by CoffeeScript 2.7.0
(function() {
  var HeyJson, fetchJson;

  fetchJson = require('./fetcher.js');

  HeyJson = class HeyJson {
    constructor(hey = {}) {
      this.runName = this.runName.bind(this);
      this.runFetchHangoverCount = this.runFetchHangoverCount.bind(this);
      this.runFetchHangoverCompare = this.runFetchHangoverCompare.bind(this);
      this.twMakeTid = this.twMakeTid.bind(this);
      this.runFetch = this.runFetch.bind(this);
      this.twFilter = this.twFilter.bind(this);
      this.twAddtid = this.twAddtid.bind(this);
      this.runMsg = this.runMsg.bind(this);
      this.hey = hey;
    }

    runName() {
      return this.hey;
    }

    async runFetchHangoverCount(url) {
      var e, f, json, views;
      try {
        f = (await fetchJson(url));
        json = JSON.parse(f);
        views = json.items[0].views;
        return views;
      } catch (error) {
        e = error;
        console.log(e);
        return "error fetching json in runFetch method";
      }
    }

    async runFetchHangoverCompare(day1, day2) {
      var d1, d2, e, msg, wikipedia;
      try {
        wikipedia = async(day) => {
          var f, json, url, views;
          url = "https://wikimedia.org/api/rest_v1/metrics/pageviews/per-article/en.wikipedia/all-access/all-agents/Philosophy/daily/" + day + "/" + day;
          f = (await fetchJson(url));
          json = JSON.parse(f);
          views = json.items[0].views;
          return views;
        };
        d1 = (await wikipedia(day1));
        d2 = (await wikipedia(day2));
        msg = "On " + day1 + " there were " + d1 + " views. On " + day2 + " there were " + d2 + " views. Interesting!";
        await this.twMakeTid("HangoverCompare", msg);
        return "success";
      } catch (error) {
        e = error;
        console.log(e);
        return "error in runFetchHangoverCompare method";
      }
    }

    twMakeTid(tid, text) {
      var body, e, title;
      console.log("running runMakeTid method");
      try {
        title = tid;
        body = text;
        return $tw.wiki.addTiddler({
          title: title,
          text: body,
          tags: "test"
        });
      } catch (error) {
        e = error;
        console.log(e);
        return "error making tiddler in runMakeTid method";
      }
    }

    async runFetch(url) {
      var e, f;
      try {
        f = (await fetchJson(url));
        return f;
      } catch (error) {
        e = error;
        console.log(e);
        return "error fetching json in runFetch method";
      }
    }

    async twFilter(filter) {
      var e, f;
      try {
        f = (await $tw.wiki.filterTiddlers(filter));
        return f;
      } catch (error) {
        e = error;
        console.log(e);
        return "error filtering tiddlers in twFilter method";
      }
    }

    async twAddtid(tid) {
      var e;
      try {
        await $tw.wiki.addTiddler(tid);
        return "added tiddler";
      } catch (error) {
        e = error;
        console.log(e);
        return "error adding tiddler in twAddtid method";
      }
    }

    runMsg() {
      var msg;
      msg = "hello there";
      return msg;
    }

  };

  module.exports = HeyJson;

}).call(this);
